export const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES: 'category/SET_CATEGORIES_MAP',
    FETCH_CATEGORIES_START: 'category/FATCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'category/FATCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'category/FATCH_CATEGORIES_FAILED',
};